### ISSUE TITLE
Usage of zipp.Path causes attempt to write after ZipFile is closed

### ISSUE THREAD

**Issue by nwh** [jaraco/zipp#57]
Hello! I am attempting to use `zipp.Path` to construct a zip archive. I encountered the following issue:

```python
import io
from zipfile import ZipFile
import zipp

def make_zip():
    """Make zip file and return bytes."""
    bytes_io = io.BytesIO()
    zip_file = ZipFile(bytes_io, mode="w")
    zipp_path = zipp.Path(zip_file)
    
    # use zipp.Path.open
    with zipp_path.joinpath("file-a").open(mode="wb") as fp:
        fp.write(b"contents of file-a")

    zip_file.close()

    data = bytes_io.getvalue()

    bytes_io.close()
    
    return data

zip_data = make_zip()
# Exception ignored in: <bound method ZipFile.__del__ of <zipp.CompleteDirs [closed]>>
# Traceback (most recent call last):
#   File "/Users/nw_henderson/.pyenv/versions/3.6.10/lib/python3.6/zipfile.py", line 1686, in __del__
#     self.close()
#   File "/Users/nw_henderson/.pyenv/versions/3.6.10/lib/python3.6/zipfile.py", line 1703, in close
#     self.fp.seek(self.start_dir)
# ValueError: I/O operation on closed file.
```

Following the [zipfile](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.close) docs, I call `close()` before extracting the data from `bytes_io`. It looks like `zipp.Path` keeps some other reference to the file object and attempts to write when `make_zip` returns and objects are cleaned up.  Python 3.8 exhibits the same issue.

**Comment by jaraco** [comment]
Thanks for the report. I'm following the [issue upstream](https://bugs.python.org/issue41350).
