### ISSUE TITLE
Install breaks on python 2.7

### ISSUE THREAD

**Issue by larryon** [jaraco/zipp#70]
https://github.com/jaraco/zipp/blob/13fad1d6a6218f44dba59550c841cbd08f2364ae/setup.cfg#L18 this might be breaking the installation

```
https://files.pythonhosted.org/packages/38/f9/4fa6df2753ded1bcc1ce2fdd8046f78bd240ff7647f5c9bcf547c0df77e3/zipp-3.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-XfEYNu/zipp/setup.py", line 6, in <module>
        setuptools.setup()
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 125, in setup
        dist.parse_config_files()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 701, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 116, in parse_configuration
        options.parse()
      File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 576, in _parse_packages
        'find_namespace: directive is unsupported on Python < 3.3')
    distutils.errors.DistutilsOptionError: find_namespace: directive is unsupported on Python < 3.3
```

**Comment by jaraco** [comment]
This current code only [supports Python 3.6 and later](https://github.com/jaraco/zipp/blob/13fad1d6a6218f44dba59550c841cbd08f2364ae/setup.cfg#L21). It [dropped support for Python 2 in the 2.0 release](https://zipp.readthedocs.io/en/latest/history.html#v2-0-0). If you install the 2.0 release on Python 2.7, it works just fine.

**Comment by jaraco** [comment]
In discord, some have proposed that pip 9 might be to blame, but even pip 9 honors the required Python version and installs the wheel:

```
$ docker run -it jaraco/multipy-tox python2.7 -m pip-run 'pip<10' -- -m pip-run --no-deps zipp -- -c pass
Collecting pip<10
  Downloading pip-9.0.3-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 1.1 MB/s 
Installing collected packages: pip
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
pip-run 6.2.0 requires pip>=19.3, but you'll have pip 9.0.3 which is incompatible.
Successfully installed pip-9.0.3
Collecting zipp
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/96/0a/67556e9b7782df7118c1f49bdc494da5e5e429c93aa77965f33e81287c8c/zipp-1.2.0-py2.py3-none-any.whl
Installing collected packages: zipp
Successfully installed zipp-1.2.0
You are using pip version 9.0.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by jaraco** [comment]
It installs fine from source too:

```
$ docker run -it jaraco/multipy-tox python2.7 -m pip-run 'pip<10' setuptools -- -m pip-run --no-deps --no-binary zipp zipp -- -c pass
Collecting pip<10
  Downloading pip-9.0.3-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 1.1 MB/s 
Collecting setuptools
  Downloading setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
     |████████████████████████████████| 583 kB 3.4 MB/s 
Installing collected packages: pip, setuptools
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
pip-run 6.2.0 requires pip>=19.3, but you'll have pip 9.0.3 which is incompatible.
Successfully installed pip-9.0.3 setuptools-44.1.1
Collecting zipp
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/78/08/d52f0ea643bc1068d6dc98b412f4966a9b63255d20911a23ac3220c033c4/zipp-1.2.0.tar.gz
Skipping bdist_wheel for zipp, due to binaries being disabled for it.
Installing collected packages: zipp
  Running setup.py install for zipp ... done
Successfully installed zipp-1.2.0
You are using pip version 9.0.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
